/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ai.spam.classifier;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SpamDetectorAppTest {
    @Test void appHasAGreeting() {
        SpamDetectorApp classUnderTest = new SpamDetectorApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
