# App identity ? shows up in /actuator/info
spring.application.name=spam-classifier
info.app.version=1.0.0
info.app.description=Naive Bayes spam classifier using OpenNLP

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs