/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ai.spam.classifier;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpamDetectorApp {

   void  main(){
       SpringApplication.run(SpamDetectorApp.class);
   }
}
